version: 2

sources:
    - name: raw
      database: raw
      schema: landing
      tables:
          - name: departments
            description: department number and name
          - name: dept_emp
            description: employees and their department
          - name: dept_manager
            description: department and their manager
          - name: employees
            description: employee details
          - name: salaries
            description: employees and their salary
          - name: titles
            description: title id and name